name: flutter_excel_table
description: This is a tool that can help you achieve Excel-style formatting in your projects.
version: 0.0.1+1
homepage: https://github.com/qipengxiang/flutter_excel

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

